"""
WordPress Theme Generator using Deep Agents

Usage:
    python app.py                           # Run demo
    python app.py --multi                   # Use multi-agent approach
    python app.py --theme "My Theme" --slug my-theme --author "John Doe"

Or programmatically:
    from agents import generate_theme
    result = generate_theme(
        theme_name="My Theme",
        theme_slug="my-theme",
        author="Developer",
        uploaded_files={"index.html": "...", "style.css": "..."}
    )
"""

import argparse
import os
import sys
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

ROOT = Path(__file__).parent
WORKSPACE_ROOT = ROOT / "workspaces"

sys.path.insert(0, str(ROOT))

from agents import create_wp_agent, generate_theme


def demo(
    use_sub_agents: bool = False,
    theme_name: str = "Demo Theme",
    theme_slug: str = "demo-theme",
    author: str = "Deep Agents",
):
    """Demo: Generate a theme from example files."""
    example_dir = ROOT.parent / "examples" / "upload"

    if not example_dir.exists():
        print("Example files not found. Creating a simple demo...")
        uploaded_files = {
            "index.html": """
<!DOCTYPE html>
<html>
<head>
    <title>Demo Theme</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <nav>
            <a href="/">Home</a>
            <a href="/about">About</a>
            <a href="/contact">Contact</a>
        </nav>
    </header>
    
    <main>
        <section class="hero">
            <h1>Welcome to Demo Theme</h1>
            <p>A beautiful WordPress theme generated by AI.</p>
            <a href="/learn-more" class="btn">Learn More</a>
        </section>
        
        <section class="features">
            <h2>Our Features</h2>
            <div class="feature-grid">
                <div class="feature">
                    <h3>Feature One</h3>
                    <p>Description of feature one.</p>
                </div>
                <div class="feature">
                    <h3>Feature Two</h3>
                    <p>Description of feature two.</p>
                </div>
                <div class="feature">
                    <h3>Feature Three</h3>
                    <p>Description of feature three.</p>
                </div>
            </div>
        </section>
    </main>
    
    <footer>
        <p>&copy; 2024 Demo Theme. All rights reserved.</p>
    </footer>
</body>
</html>
""",
            "style.css": """
/* Demo Theme Styles */
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: Arial, sans-serif; line-height: 1.6; }
header { background: #333; color: #fff; padding: 1rem; }
nav a { color: #fff; text-decoration: none; margin-right: 1rem; }
nav a:hover { text-decoration: underline; }
.hero { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #fff; padding: 4rem 2rem; text-align: center; }
.hero h1 { font-size: 2.5rem; margin-bottom: 1rem; }
.btn { display: inline-block; background: #fff; color: #667eea; padding: 0.75rem 1.5rem; border-radius: 4px; text-decoration: none; margin-top: 1rem; }
.features { padding: 3rem 2rem; }
.features h2 { text-align: center; margin-bottom: 2rem; }
.feature-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 2rem; }
.feature { background: #f5f5f5; padding: 1.5rem; border-radius: 8px; }
footer { background: #333; color: #fff; text-align: center; padding: 1rem; margin-top: 2rem; }
""",
        }
    else:
        uploaded_files = {}
        for f in example_dir.iterdir():
            if f.is_file() and f.suffix in [".html", ".css", ".js"]:
                uploaded_files[f.name] = f.read_text(encoding="utf-8")

    print("=" * 60)
    print("WordPress Theme Generator (Deep Agents)")
    print("=" * 60)
    print(f"Theme: {theme_name}")
    print(f"Slug: {theme_slug}")
    print(f"Author: {author}")
    print(f"Multi-agent: {use_sub_agents}")
    print(f"Source files: {list(uploaded_files.keys())}")
    print("=" * 60)

    if use_sub_agents:
        print("\nUsing multi-agent workflow: Analyzer → Generator → ACF → Validator")

    result = generate_theme(
        theme_name=theme_name,
        theme_slug=theme_slug,
        author=author,
        uploaded_files=uploaded_files,
        use_sub_agents=use_sub_agents,
    )

    print("\n" + "=" * 60)
    print(f"Result: {'SUCCESS' if result['ok'] else 'FAILED'}")
    print(f"Theme path: {result['theme_path']}")
    print("=" * 60)

    return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate WordPress themes using Deep Agents"
    )
    parser.add_argument(
        "--multi", action="store_true", help="Use multi-agent approach (sub-agents)"
    )
    parser.add_argument("--theme", type=str, default="Demo Theme", help="Theme name")
    parser.add_argument(
        "--slug", type=str, default="demo-theme", help="Theme slug (folder name)"
    )
    parser.add_argument(
        "--author", type=str, default="Deep Agents", help="Theme author"
    )

    args = parser.parse_args()

    demo(
        use_sub_agents=args.multi,
        theme_name=args.theme,
        theme_slug=args.slug,
        author=args.author,
    )
